TABLE_PROPERTIES = {
    'write.format.default': 'parquet',
    'format-version': 2,
    'write.parquet.compression-codec': 'zstd',
    'write.metadata.delete-after-commit.enabled': 'true',
    'write.delete.mode': 'copy-on-write',
    'write.metadata.previous-versions-max': 5,
    'write.update.mode': 'merge-on-read',
    'write.merge.mode': 'merge-on-read',
    'write.distribution-mode': 'hash',
    'history.expire.max-snapshot-age-ms': 86400000,
    'history.expire.min-snapshots-to-keep': 1,
    'commit.manifest-merge.enabled': 'true',
    'commit.manifest.min-count-to-merge': 5,
    'commit.retry.num-retries': 10,
    'commit.retry.min-wait-ms': 100,
    'commit.retry.max-wait-ms': 60000,
}
